/* The following code was generated by JFlex 1.6.1 */

package compilador;
import compilador.sym;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/compilador/Lexer.flex</tt>
 */
public class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int comment = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 41, 45, 46, 46, 45,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    13, 22, 40,  0,  0,  0, 32, 39,  7,  8, 29, 30, 33, 26,  0, 44, 
    38, 38, 38, 38, 38, 38, 38, 38, 38, 38,  0, 23, 31, 28, 27,  0, 
     0, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 
    37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 42,  0, 43,  0,  4, 
     0,  6,  9, 21, 12, 10, 17, 11, 34,  1, 37, 37, 14,  5,  2, 15, 
    16, 37, 18, 19,  3, 20, 37, 37, 36, 35, 37, 24, 32, 25,  0,  0, 
     0,  0,  0,  0,  0, 46,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\3\2\1\1\2\2\1\3\1\4\2\2"+
    "\1\5\6\2\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\12\1\16\1\17\1\20\2\1\1\21"+
    "\1\22\1\15\1\5\2\23\1\24\1\23\1\25\1\0"+
    "\16\23\1\13\1\26\3\0\1\27\1\30\1\31\10\23"+
    "\1\32\2\23\1\33\4\23\1\34\1\35\1\0\1\36"+
    "\3\23\1\31\1\0\1\37\1\40\1\23\1\0\1\23"+
    "\1\41\1\23\1\42\1\0\2\23\1\43\6\0\1\23"+
    "\1\0\1\44\1\23\2\0\1\45\6\0\1\23\1\0"+
    "\1\46\10\0\1\47\1\0\1\50\1\51\4\0\1\52"+
    "\1\53\1\54\1\0\1\55\1\0\1\31\3\0\1\56"+
    "\1\0\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\136\0\136\0\u01a7\0\u01d6\0\136\0\u0205\0\u0234"+
    "\0\u0263\0\u0292\0\u02c1\0\u02f0\0\u031f\0\136\0\136\0\136"+
    "\0\u034e\0\u031f\0\u031f\0\136\0\136\0\136\0\136\0\u037d"+
    "\0\u03ac\0\u03db\0\136\0\136\0\u040a\0\u0439\0\274\0\u0468"+
    "\0\274\0\u0497\0\u011a\0\u04c6\0\u04f5\0\u0524\0\u0553\0\u0582"+
    "\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d\0\u069c\0\u06cb\0\u06fa"+
    "\0\u0729\0\u0758\0\136\0\136\0\u0787\0\u07b6\0\u07e5\0\136"+
    "\0\136\0\u0814\0\u0843\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e"+
    "\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0a19\0\274\0\u0a48\0\u0a77"+
    "\0\u0aa6\0\u0ad5\0\136\0\136\0\u0b04\0\274\0\u0b33\0\u0b62"+
    "\0\u0b91\0\274\0\u0bc0\0\274\0\274\0\u0bef\0\u0c1e\0\u0c4d"+
    "\0\274\0\u0c7c\0\274\0\u0cab\0\u0cda\0\u0d09\0\274\0\u0d38"+
    "\0\u0d67\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\274"+
    "\0\u0eb0\0\u0edf\0\u0f0e\0\136\0\u0f3d\0\u0f6c\0\u0f9b\0\u0fca"+
    "\0\u0ff9\0\u1028\0\u1057\0\u1086\0\274\0\u10b5\0\u10e4\0\u1113"+
    "\0\u1142\0\u1171\0\u11a0\0\u11cf\0\u11fe\0\136\0\u122d\0\274"+
    "\0\136\0\u125c\0\u128b\0\u12ba\0\u12e9\0\136\0\136\0\136"+
    "\0\u1318\0\136\0\u1347\0\136\0\u1376\0\u13a5\0\u13d4\0\136"+
    "\0\u1403\0\136";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\2\5\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\2\5\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\32\1\36\1\37"+
    "\4\5\1\40\1\41\1\42\1\16\1\43\1\44\1\45"+
    "\1\16\1\0\35\16\1\46\17\16\62\0\1\47\1\50"+
    "\1\47\1\0\2\47\2\0\4\47\1\0\3\47\1\51"+
    "\4\47\14\0\4\47\12\0\3\47\1\0\2\47\2\0"+
    "\4\47\1\0\10\47\14\0\4\47\12\0\3\47\1\0"+
    "\2\47\2\0\4\47\1\0\4\47\1\52\3\47\14\0"+
    "\4\47\12\0\3\53\1\0\2\53\2\0\4\53\1\0"+
    "\10\53\4\0\1\54\7\0\5\53\11\0\3\47\1\0"+
    "\1\47\1\55\2\0\4\47\1\0\10\47\14\0\4\47"+
    "\12\0\3\47\1\0\2\47\2\0\4\47\1\0\4\47"+
    "\1\56\3\47\14\0\4\47\12\0\3\47\1\0\2\47"+
    "\2\0\1\47\1\57\2\47\1\0\1\47\1\60\6\47"+
    "\14\0\4\47\12\0\1\47\1\61\1\47\1\0\2\47"+
    "\2\0\4\47\1\0\1\62\7\47\14\0\4\47\12\0"+
    "\3\47\1\0\2\47\2\0\4\47\1\0\1\47\1\63"+
    "\6\47\14\0\4\47\12\0\3\47\1\0\2\47\2\0"+
    "\4\47\1\0\2\47\1\64\5\47\14\0\4\47\12\0"+
    "\3\47\1\0\2\47\2\0\4\47\1\0\4\47\1\65"+
    "\3\47\14\0\4\47\12\0\3\47\1\0\1\47\1\66"+
    "\2\0\4\47\1\0\1\47\1\67\4\47\1\70\1\47"+
    "\14\0\4\47\12\0\3\47\1\0\2\47\2\0\1\47"+
    "\1\71\2\47\1\0\10\47\14\0\4\47\12\0\3\47"+
    "\1\0\2\47\2\0\4\47\1\0\10\47\14\0\1\72"+
    "\3\47\45\0\1\73\55\0\1\74\12\0\1\40\56\0"+
    "\1\40\11\0\3\75\1\0\2\75\2\0\15\75\14\0"+
    "\5\75\11\0\3\76\1\0\2\76\2\0\15\76\4\0"+
    "\1\77\7\0\5\76\2\0\1\76\3\0\1\76\36\0"+
    "\1\100\75\0\1\101\3\0\2\47\1\102\1\0\2\47"+
    "\2\0\4\47\1\0\10\47\14\0\4\47\12\0\3\47"+
    "\1\0\2\47\2\0\4\47\1\0\6\47\1\103\1\47"+
    "\14\0\4\47\57\0\1\53\11\0\2\47\1\104\1\0"+
    "\2\47\2\0\4\47\1\0\10\47\14\0\4\47\12\0"+
    "\3\47\1\0\2\47\2\0\4\47\1\0\4\47\1\105"+
    "\3\47\14\0\4\47\12\0\3\47\1\0\2\47\2\0"+
    "\2\47\1\106\1\47\1\0\10\47\14\0\4\47\12\0"+
    "\3\47\1\0\2\47\2\0\4\47\1\0\1\47\1\107"+
    "\6\47\14\0\4\47\12\0\3\47\1\0\2\47\2\0"+
    "\3\47\1\110\1\0\10\47\14\0\4\47\12\0\3\47"+
    "\1\0\2\47\2\0\4\47\1\0\5\47\1\111\2\47"+
    "\14\0\4\47\12\0\3\47\1\0\2\47\2\0\4\47"+
    "\1\0\1\47\1\112\6\47\14\0\4\47\12\0\2\47"+
    "\1\113\1\0\2\47\2\0\4\47\1\0\10\47\14\0"+
    "\4\47\12\0\1\114\2\47\1\0\2\47\2\0\4\47"+
    "\1\0\10\47\14\0\4\47\12\0\3\47\1\0\2\47"+
    "\2\0\4\47\1\0\1\115\7\47\14\0\4\47\12\0"+
    "\3\47\1\0\2\47\2\0\4\47\1\0\4\47\1\116"+
    "\3\47\14\0\4\47\12\0\1\47\1\117\1\47\1\0"+
    "\2\47\2\0\4\47\1\0\10\47\14\0\4\47\12\0"+
    "\2\47\1\120\1\0\1\47\1\121\2\0\4\47\1\0"+
    "\10\47\14\0\4\47\12\0\3\47\1\0\1\47\1\122"+
    "\2\0\4\47\1\0\10\47\14\0\4\47\60\0\1\123"+
    "\10\0\3\76\1\0\2\76\2\0\15\76\4\0\1\77"+
    "\7\0\5\76\1\0\1\124\1\76\3\0\1\76\47\0"+
    "\1\76\11\0\3\47\1\125\2\47\2\0\4\47\1\0"+
    "\10\47\14\0\4\47\12\0\3\47\1\0\2\47\2\0"+
    "\1\47\1\126\2\47\1\0\10\47\14\0\4\47\12\0"+
    "\3\47\1\0\2\47\2\0\4\47\1\0\4\47\1\127"+
    "\3\47\14\0\4\47\12\0\3\47\1\0\1\47\1\130"+
    "\2\0\4\47\1\0\10\47\14\0\4\47\12\0\1\131"+
    "\2\47\1\0\2\47\2\0\4\47\1\0\10\47\14\0"+
    "\4\47\12\0\3\47\1\0\2\47\2\0\4\47\1\0"+
    "\1\132\7\47\14\0\4\47\12\0\3\47\1\0\2\47"+
    "\2\0\4\47\1\133\10\47\14\0\4\47\12\0\3\47"+
    "\1\0\2\47\2\0\1\47\1\134\2\47\1\0\10\47"+
    "\14\0\4\47\12\0\3\47\1\0\2\47\2\0\4\47"+
    "\1\0\2\47\1\135\5\47\14\0\4\47\12\0\1\136"+
    "\2\47\1\137\2\47\2\0\4\47\1\0\10\47\14\0"+
    "\4\47\12\0\1\47\1\140\1\47\1\0\2\47\2\0"+
    "\4\47\1\0\10\47\14\0\4\47\12\0\3\47\1\0"+
    "\2\47\2\0\4\47\1\0\5\47\1\103\2\47\14\0"+
    "\4\47\12\0\3\47\1\0\2\47\2\0\4\47\1\0"+
    "\7\47\1\141\14\0\4\47\12\0\3\47\1\0\2\47"+
    "\2\0\4\47\1\0\6\47\1\142\1\47\14\0\4\47"+
    "\12\0\3\47\1\0\2\47\2\0\3\47\1\143\1\0"+
    "\10\47\14\0\4\47\12\0\3\47\1\0\2\47\2\0"+
    "\4\47\1\0\4\47\1\132\3\47\14\0\4\47\16\0"+
    "\1\144\52\0\1\145\2\47\1\0\2\47\2\0\4\47"+
    "\1\0\10\47\14\0\4\47\12\0\3\47\1\0\2\47"+
    "\2\0\4\47\1\0\10\47\14\0\1\47\1\146\2\47"+
    "\12\0\1\47\1\147\1\47\1\0\2\47\2\0\4\47"+
    "\1\0\10\47\14\0\4\47\12\0\1\150\3\0\1\151"+
    "\4\0\1\152\3\0\1\153\1\154\1\0\1\155\36\0"+
    "\3\47\1\0\2\47\2\0\4\47\1\0\1\47\1\156"+
    "\6\47\14\0\4\47\25\0\1\157\43\0\2\47\1\160"+
    "\1\0\2\47\2\0\4\47\1\0\10\47\14\0\4\47"+
    "\12\0\3\47\1\0\2\47\2\0\4\47\1\0\4\47"+
    "\1\161\3\47\14\0\4\47\17\0\1\162\51\0\3\47"+
    "\1\0\2\47\2\0\4\47\1\0\10\47\14\0\2\47"+
    "\1\146\1\47\12\0\3\47\1\163\2\47\2\0\4\47"+
    "\1\0\10\47\14\0\4\47\32\0\1\164\43\0\1\165"+
    "\66\0\1\166\57\0\1\167\57\0\1\170\55\0\1\171"+
    "\4\0\1\172\33\0\1\47\1\173\1\47\1\0\2\47"+
    "\2\0\4\47\1\0\10\47\14\0\4\47\23\0\1\174"+
    "\45\0\1\47\1\175\1\47\1\0\2\47\2\0\4\47"+
    "\1\0\10\47\14\0\4\47\12\0\1\176\56\0\1\177"+
    "\7\0\1\200\13\0\1\201\32\0\1\202\100\0\1\203"+
    "\52\0\1\204\42\0\1\205\75\0\1\206\36\0\1\207"+
    "\55\0\3\47\1\0\2\47\2\0\4\47\1\0\5\47"+
    "\1\210\2\47\14\0\4\47\32\0\1\211\37\0\1\212"+
    "\56\0\1\213\73\0\1\214\101\0\1\215\16\0\1\216"+
    "\66\0\1\217\64\0\1\220\37\0\1\221\102\0\1\222"+
    "\40\0\1\223\52\0\1\224\72\0\1\225\45\0\1\226"+
    "\67\0\1\227\47\0\1\230\64\0\1\224\62\0\1\224"+
    "\36\0\1\231\77\0\1\232\33\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5170];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\6\1\2\11\2\1\1\11\7\1\3\11"+
    "\3\1\4\11\3\1\2\11\7\1\1\0\16\1\2\11"+
    "\3\0\2\11\21\1\2\11\1\0\5\1\1\0\3\1"+
    "\1\0\4\1\1\0\3\1\6\0\1\1\1\0\2\1"+
    "\2\0\1\11\6\0\1\1\1\0\1\1\10\0\1\11"+
    "\1\0\1\1\1\11\4\0\3\11\1\0\1\11\1\0"+
    "\1\11\3\0\1\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public String error = "";


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { error += "No reconoce: " + yytext() + " linea: " + (yyline+1) + " columna: "+(yycolumn+1) + "\n"; return new Symbol(sym.error, yyline, yycolumn,yytext());
            }
          case 48: break;
          case 2: 
            { error += "No se esperaba la letra: " + yytext() + " linea: " + yyline + " columna: "+yycolumn + "\n"; return new Symbol(sym.error, yyline, yycolumn,yytext());
            }
          case 49: break;
          case 3: 
            { return new Symbol(sym.ABREPAR, yyline, yycolumn,yytext());
            }
          case 50: break;
          case 4: 
            { return new Symbol(sym.CIERRAPAR, yyline, yycolumn,yytext());
            }
          case 51: break;
          case 5: 
            { 
            }
          case 52: break;
          case 6: 
            { return new Symbol(sym.NOT, yyline, yycolumn,yytext());
            }
          case 53: break;
          case 7: 
            { return new Symbol(sym.FINLINE, yyline, yycolumn,yytext());
            }
          case 54: break;
          case 8: 
            { return new Symbol(sym.ABRE, yyline, yycolumn,yytext());
            }
          case 55: break;
          case 9: 
            { return new Symbol(sym.CIERRA, yyline, yycolumn,yytext());
            }
          case 56: break;
          case 10: 
            { return new Symbol(sym.OPSR, yyline, yycolumn,yytext());
            }
          case 57: break;
          case 11: 
            { return new Symbol(sym.OPREL, yyline, yycolumn,yytext());
            }
          case 58: break;
          case 12: 
            { return new Symbol(sym.ASIG, yyline, yycolumn,yytext());
            }
          case 59: break;
          case 13: 
            { return new Symbol(sym.OPMD, yyline, yycolumn,yytext());
            }
          case 60: break;
          case 14: 
            { return new Symbol(sym.ANDOR, yyline, yycolumn,yytext());
            }
          case 61: break;
          case 15: 
            { return new Symbol(sym.COMA, yyline, yycolumn,yytext());
            }
          case 62: break;
          case 16: 
            { return new Symbol(sym.INT, yyline, yycolumn,yytext());
            }
          case 63: break;
          case 17: 
            { return new Symbol(sym.ABRECOR, yyline, yycolumn,yytext());
            }
          case 64: break;
          case 18: 
            { return new Symbol(sym.CIERRACOR, yyline, yycolumn,yytext());
            }
          case 65: break;
          case 19: 
            { error += "No se esperaba: " + yytext() + " linea: " + (yyline+1) + " columna: "+(yycolumn+1) + "\n"; return new Symbol(sym.error, yyline, yycolumn,yytext());
            }
          case 66: break;
          case 20: 
            { return new Symbol(sym.IF, yyline, yycolumn,yytext());
            }
          case 67: break;
          case 21: 
            { return new Symbol(sym.ID, yyline, yycolumn,yytext());
            }
          case 68: break;
          case 22: 
            { return new Symbol(sym.HASTA, yyline, yycolumn,yytext());
            }
          case 69: break;
          case 23: 
            { yybegin(comment);
            }
          case 70: break;
          case 24: 
            { yybegin(YYINITIAL);
            }
          case 71: break;
          case 25: 
            { return new Symbol(sym.TYPE, yyline, yycolumn,yytext());
            }
          case 72: break;
          case 26: 
            { return new Symbol(sym.OPT, yyline, yycolumn,yytext());
            }
          case 73: break;
          case 27: 
            { return new Symbol(sym.FOR, yyline, yycolumn,yytext());
            }
          case 74: break;
          case 28: 
            { return new Symbol(sym.CHAR, yyline, yycolumn,yytext());
            }
          case 75: break;
          case 29: 
            { return new Symbol(sym.STRING, yyline, yycolumn,yytext());
            }
          case 76: break;
          case 30: 
            { return new Symbol(sym.BOOL, yyline, yycolumn,yytext());
            }
          case 77: break;
          case 31: 
            { return new Symbol(sym.ELSE, yyline, yycolumn,yytext());
            }
          case 78: break;
          case 32: 
            { return new Symbol(sym.LOOP, yyline, yycolumn,yytext());
            }
          case 79: break;
          case 33: 
            { return new Symbol(sym.FUNC, yyline, yycolumn,yytext());
            }
          case 80: break;
          case 34: 
            { return new Symbol(sym.READ, yyline, yycolumn,yytext());
            }
          case 81: break;
          case 35: 
            { return new Symbol(sym.BEGIN, yyline, yycolumn,yytext());
            }
          case 82: break;
          case 36: 
            { return new Symbol(sym.PRINT, yyline, yycolumn,yytext());
            }
          case 83: break;
          case 37: 
            { return new Symbol(sym.ENDI, yyline, yycolumn,yytext());
            }
          case 84: break;
          case 38: 
            { return new Symbol(sym.RETURN, yyline, yycolumn,yytext());
            }
          case 85: break;
          case 39: 
            { return new Symbol(sym.ENDF, yyline, yycolumn,yytext());
            }
          case 86: break;
          case 40: 
            { return new Symbol(sym.OPTIONS, yyline, yycolumn,yytext());
            }
          case 87: break;
          case 41: 
            { return new Symbol(sym.DEFOPT, yyline, yycolumn,yytext());
            }
          case 88: break;
          case 42: 
            { return new Symbol(sym.ENDM, yyline, yycolumn,yytext());
            }
          case 89: break;
          case 43: 
            { return new Symbol(sym.ENDE, yyline, yycolumn,yytext());
            }
          case 90: break;
          case 44: 
            { return new Symbol(sym.ENDL, yyline, yycolumn,yytext());
            }
          case 91: break;
          case 45: 
            { return new Symbol(sym.ENDFU, yyline, yycolumn,yytext());
            }
          case 92: break;
          case 46: 
            { return new Symbol(sym.MAIN, yyline, yycolumn,yytext());
            }
          case 93: break;
          case 47: 
            { return new Symbol(sym.ENDO, yyline, yycolumn,yytext());
            }
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
