/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;

/**
 *
 * @author edujg
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Seleccionar Archivo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jButton1.setText("Buscar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jButton2.setText("Analizar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try {
            // TODO add your handling code here:
            AnalizadorLexico lexico = new AnalizadorLexico(new FileReader("C:/Users/edujg/Desktop/Eduardo/Compilador/src/compilador/teste.txt"));
            String result = "";
            ArrayList<Token> tokens = new ArrayList<Token>();
            while (true) {
                Symbol tok = lexico.next_token();
                if (tok.sym == sym.EOF) {
                    System.out.println("Analisis Lexico");
                    if (!lexico.error.equals("")) {
                        System.out.println(lexico.error);
                    }else{
                        System.out.println("No se encontraron errores lexicos");
                    }
                    break;
                } else {
                    if(tok.sym != sym.error){
                        tokens.add(new Token(tok.value.toString(), tok.sym));
                    }
                }
            }
            if(!lexico.error.equals("")){
                File file = new File("C:/Users/edujg/Desktop/Eduardo/Compilador/src/compilador/correcion.txt");
                FileWriter f = new FileWriter("C:/Users/edujg/Desktop/Eduardo/Compilador/src/compilador/correccion.txt");
                for (int i = 0; i < tokens.size(); i++) {
                    result += tokens.get(i).valor + " ";
                }
                f.write(result);
                f.close();
                lexico = new AnalizadorLexico(new FileReader("C:/Users/edujg/Desktop/Eduardo/Compilador/src/compilador/correccion.txt"));
            }else{
                lexico = new AnalizadorLexico(new FileReader("C:/Users/edujg/Desktop/Eduardo/Compilador/src/compilador/teste.txt"));
            }
            System.out.println("");
            System.out.println("Analisis Sintactico");
            parser parser = new parser(lexico);
            parser.parse();
            if(!parser.error.equals("")){
                System.out.println(parser.error);
            }else{
                System.out.println("No se encontraron errores lexicos");
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //generateLexer();
                System.out.println("NOTE TO SELF, INCLUIR EN LAS GRAMATICAS LOS ARREGLOS Y MATRIZES Y SEPARAR VALOR");
                new Interfaz().setVisible(true);
            }
        });
    }

    public static void generateLexer() {
        String[] param = new String[3];
        param[0] = "-d";
        param[1] = "src/compilador";
        param[2] = "src/compilador/Lexer.flex";
        String[] param2 = {"-destdir", "src/compilador/", "-parser", "parser", "src/compilador/Cup.cup"};
        try {
            jflex.Main.generate(param);
            System.out.println("Funciono1");
            java_cup.Main.main(param2);
            System.out.println("Funciono2");
        } catch (Exception e) {
            System.out.println("No funciono");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
