
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 16 15:52:43 CST 2020
//----------------------------------------------------

package compilador;

import java_cup.runtime.Symbol;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed Sep 16 15:52:43 CST 2020
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\103\000\002\002\004\000\002\002\004\000\002\002" +
    "\002\000\002\003\014\000\002\020\004\000\002\020\006" +
    "\000\002\020\002\000\002\021\006\000\002\021\004\000" +
    "\002\013\011\000\002\004\005\000\002\022\006\000\002" +
    "\022\004\000\002\023\004\000\002\023\002\000\002\005" +
    "\006\000\002\006\011\000\002\007\013\000\002\007\006" +
    "\000\002\010\020\000\002\011\011\000\002\012\013\000" +
    "\002\024\012\000\002\024\006\000\002\040\003\000\002" +
    "\014\007\000\002\025\003\000\002\025\003\000\002\015" +
    "\005\000\002\015\003\000\002\026\005\000\002\026\003" +
    "\000\002\027\003\000\002\027\003\000\002\027\005\000" +
    "\002\016\005\000\002\016\003\000\002\030\005\000\002" +
    "\030\003\000\002\031\006\000\002\031\003\000\002\031" +
    "\003\000\002\032\003\000\002\032\002\000\002\017\004" +
    "\000\002\017\004\000\002\017\004\000\002\017\005\000" +
    "\002\017\004\000\002\017\004\000\002\017\004\000\002" +
    "\017\004\000\002\017\002\000\002\033\005\000\002\035" +
    "\005\000\002\041\005\000\002\041\003\000\002\036\005" +
    "\000\002\042\005\000\002\042\003\000\002\037\003\000" +
    "\002\037\003\000\002\034\003\000\002\034\003\000\002" +
    "\034\003\000\002\043\003\000\002\043\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\254\000\004\036\uffff\001\002\000\004\002\256\001" +
    "\002\000\004\036\006\001\002\000\006\007\010\035\011" +
    "\001\002\000\004\036\000\001\002\000\004\014\252\001" +
    "\002\000\004\040\012\001\002\000\004\041\013\001\002" +
    "\000\006\035\016\042\ufffb\001\002\000\004\033\247\001" +
    "\002\000\004\042\020\001\002\000\004\040\017\001\002" +
    "\000\006\033\ufff9\042\ufffd\001\002\000\004\014\021\001" +
    "\002\000\022\006\027\010\024\011\026\034\uffcd\035\032" +
    "\037\031\040\033\044\036\001\002\000\004\034\243\001" +
    "\002\000\034\006\027\010\024\011\026\017\uffcd\020\uffcd" +
    "\021\uffcd\023\uffcd\026\uffcd\034\uffcd\035\032\037\031\040" +
    "\033\044\036\001\002\000\004\041\224\001\002\000\034" +
    "\006\027\010\024\011\026\017\uffcd\020\uffcd\021\uffcd\023" +
    "\uffcd\026\uffcd\034\uffcd\035\032\037\031\040\033\044\036" +
    "\001\002\000\004\041\176\001\002\000\004\041\170\001" +
    "\002\000\034\006\027\010\024\011\026\017\uffcd\020\uffcd" +
    "\021\uffcd\023\uffcd\026\uffcd\034\uffcd\035\032\037\031\040" +
    "\033\044\036\001\002\000\004\041\161\001\002\000\004" +
    "\040\150\001\002\000\004\030\145\001\002\000\034\006" +
    "\027\010\024\011\026\017\uffcd\020\uffcd\021\uffcd\023\uffcd" +
    "\026\uffcd\034\uffcd\035\032\037\031\040\033\044\036\001" +
    "\002\000\034\006\027\010\024\011\026\017\uffcd\020\uffcd" +
    "\021\uffcd\023\uffcd\026\uffcd\034\uffcd\035\032\037\031\040" +
    "\033\044\036\001\002\000\004\041\076\001\002\000\034" +
    "\006\027\010\024\011\026\017\uffcd\020\uffcd\021\uffcd\023" +
    "\uffcd\026\uffcd\034\uffcd\035\032\037\031\040\033\044\036" +
    "\001\002\000\036\006\027\010\024\011\026\017\uffcd\020" +
    "\uffcd\021\uffcd\023\uffcd\026\uffcd\034\uffcd\035\032\037\031" +
    "\040\033\043\042\044\036\001\002\000\016\017\uffd3\020" +
    "\uffd3\021\uffd3\023\uffd3\026\uffd3\034\uffd3\001\002\000\006" +
    "\014\045\037\046\001\002\000\034\006\027\010\024\011" +
    "\026\017\uffcd\020\uffcd\021\uffcd\023\uffcd\026\uffcd\034\uffcd" +
    "\035\032\037\031\040\033\044\036\001\002\000\016\017" +
    "\uffd2\020\uffd2\021\uffd2\023\uffd2\026\uffd2\034\uffd2\001\002" +
    "\000\022\006\027\010\024\011\026\020\uffcd\035\032\037" +
    "\031\040\033\044\036\001\002\000\004\041\047\001\002" +
    "\000\012\040\050\041\uffd6\047\056\051\053\001\002\000" +
    "\010\004\uffd8\005\uffd8\042\uffd8\001\002\000\006\005\063" +
    "\042\066\001\002\000\004\041\061\001\002\000\004\041" +
    "\uffd7\001\002\000\010\004\uffdb\005\uffdb\042\uffdb\001\002" +
    "\000\010\004\057\005\uffdd\042\uffdd\001\002\000\010\004" +
    "\uffd9\005\uffd9\042\uffd9\001\002\000\012\040\050\041\uffd6" +
    "\047\056\051\053\001\002\000\010\004\uffdc\005\uffdc\042" +
    "\uffdc\001\002\000\012\040\050\041\uffd6\047\056\051\053" +
    "\001\002\000\006\005\063\042\064\001\002\000\012\040" +
    "\050\041\uffd6\047\056\051\053\001\002\000\010\004\uffda" +
    "\005\uffda\042\uffda\001\002\000\010\004\057\005\uffde\042" +
    "\uffde\001\002\000\004\014\067\001\002\000\022\006\027" +
    "\010\024\011\026\020\uffcd\035\032\037\031\040\033\044" +
    "\036\001\002\000\004\020\071\001\002\000\004\043\042" +
    "\001\002\000\034\006\ufff0\010\ufff0\011\ufff0\017\ufff0\020" +
    "\ufff0\021\ufff0\023\ufff0\026\ufff0\034\ufff0\035\ufff0\037\ufff0" +
    "\040\ufff0\044\ufff0\001\002\000\004\020\074\001\002\000" +
    "\034\006\uffef\010\uffef\011\uffef\017\uffef\020\uffef\021\uffef" +
    "\023\uffef\026\uffef\034\uffef\035\uffef\037\uffef\040\uffef\044" +
    "\uffef\001\002\000\016\017\uffd1\020\uffd1\021\uffd1\023\uffd1" +
    "\026\uffd1\034\uffd1\001\002\000\016\040\113\041\110\045" +
    "\100\046\115\047\101\050\106\001\002\000\012\024\uffc0" +
    "\033\uffc0\042\uffc0\053\uffc0\001\002\000\016\024\uffe1\031" +
    "\uffe1\032\uffe1\033\uffe1\042\uffe1\053\uffe1\001\002\000\012" +
    "\024\uffc4\033\uffc4\042\uffc4\053\uffc4\001\002\000\016\024" +
    "\uffe2\031\uffe2\032\uffe2\033\uffe2\042\uffe2\053\uffe2\001\002" +
    "\000\004\042\uffe7\001\002\000\016\024\uffe4\031\136\032" +
    "\uffe4\033\uffe4\042\uffe4\053\uffe4\001\002\000\014\024\uffbf" +
    "\032\133\033\uffbf\042\uffbf\053\uffbf\001\002\000\004\042" +
    "\uffe6\001\002\000\012\024\uffc1\033\uffc1\042\uffc1\053\uffc1" +
    "\001\002\000\014\040\113\041\124\045\100\046\115\047" +
    "\101\001\002\000\004\042\116\001\002\000\012\024\uffc3" +
    "\033\uffc3\042\uffc3\053\uffc3\001\002\000\016\024\uffe0\031" +
    "\uffe0\032\uffe0\033\uffe0\042\uffe0\053\uffe0\001\002\000\012" +
    "\024\uffc2\033\uffc2\042\uffc2\053\uffc2\001\002\000\012\024" +
    "\uffc5\033\uffc5\042\uffc5\053\uffc5\001\002\000\004\024\117" +
    "\001\002\000\034\006\uffe8\010\uffe8\011\uffe8\017\uffe8\020" +
    "\uffe8\021\uffe8\023\uffe8\026\uffe8\034\uffe8\035\uffe8\037\uffe8" +
    "\040\uffe8\044\uffe8\001\002\000\006\033\140\042\141\001" +
    "\002\000\006\032\133\042\134\001\002\000\006\033\127" +
    "\042\130\001\002\000\006\033\uffc9\042\uffc9\001\002\000" +
    "\014\040\113\041\126\045\100\046\115\047\101\001\002" +
    "\000\006\033\uffc6\042\uffc6\001\002\000\010\040\113\041" +
    "\126\045\100\001\002\000\004\041\131\001\002\000\012" +
    "\024\uffc8\033\uffc8\042\uffc8\053\uffc8\001\002\000\006\046" +
    "\115\047\101\001\002\000\006\033\uffc7\042\uffc7\001\002" +
    "\000\010\040\113\041\126\045\100\001\002\000\016\024" +
    "\uffdf\031\uffdf\032\uffdf\033\uffdf\042\uffdf\053\uffdf\001\002" +
    "\000\016\024\uffe5\031\136\032\uffe5\033\uffe5\042\uffe5\053" +
    "\uffe5\001\002\000\010\040\113\041\126\045\100\001\002" +
    "\000\016\024\uffe3\031\uffe3\032\uffe3\033\uffe3\042\uffe3\053" +
    "\uffe3\001\002\000\006\046\115\047\101\001\002\000\012" +
    "\024\uffcb\033\uffcb\042\uffcb\053\uffcb\001\002\000\006\033" +
    "\uffca\042\uffca\001\002\000\016\017\uffd4\020\uffd4\021\uffd4" +
    "\023\uffd4\026\uffd4\034\uffd4\001\002\000\016\017\uffce\020" +
    "\uffce\021\uffce\023\uffce\026\uffce\034\uffce\001\002\000\014" +
    "\040\113\041\110\045\100\046\115\047\101\001\002\000" +
    "\004\024\147\001\002\000\034\006\ufff2\010\ufff2\011\ufff2" +
    "\017\ufff2\020\ufff2\021\ufff2\023\ufff2\026\ufff2\034\ufff2\035" +
    "\ufff2\037\ufff2\040\ufff2\044\ufff2\001\002\000\010\024\ufff3" +
    "\030\156\033\ufff3\001\002\000\006\024\153\033\152\001" +
    "\002\000\004\040\154\001\002\000\034\006\ufff7\010\ufff7" +
    "\011\ufff7\017\ufff7\020\ufff7\021\ufff7\023\ufff7\026\ufff7\034" +
    "\ufff7\035\ufff7\037\ufff7\040\ufff7\044\ufff7\001\002\000\010" +
    "\024\ufff3\030\156\033\ufff3\001\002\000\006\024\ufff6\033" +
    "\ufff6\001\002\000\014\040\113\041\110\045\100\046\115" +
    "\047\101\001\002\000\006\024\ufff4\033\ufff4\001\002\000" +
    "\006\024\ufff5\033\ufff5\001\002\000\012\040\050\041\uffd6" +
    "\047\056\051\053\001\002\000\006\005\063\042\163\001" +
    "\002\000\004\014\164\001\002\000\022\006\027\010\024" +
    "\011\026\017\uffcd\035\032\037\031\040\033\044\036\001" +
    "\002\000\004\017\166\001\002\000\036\006\ufff1\010\ufff1" +
    "\011\ufff1\017\ufff1\020\ufff1\021\ufff1\023\ufff1\026\ufff1\034" +
    "\ufff1\035\ufff1\037\ufff1\040\ufff1\043\ufff1\044\ufff1\001\002" +
    "\000\016\017\uffcf\020\uffcf\021\uffcf\023\uffcf\026\uffcf\034" +
    "\uffcf\001\002\000\012\040\050\041\uffd6\047\056\051\053" +
    "\001\002\000\006\005\063\042\172\001\002\000\004\014" +
    "\173\001\002\000\022\006\027\010\024\011\026\023\uffcd" +
    "\035\032\037\031\040\033\044\036\001\002\000\004\023" +
    "\175\001\002\000\034\006\uffed\010\uffed\011\uffed\017\uffed" +
    "\020\uffed\021\uffed\023\uffed\026\uffed\034\uffed\035\uffed\037" +
    "\uffed\040\uffed\044\uffed\001\002\000\004\040\177\001\002" +
    "\000\004\033\200\001\002\000\004\035\201\001\002\000" +
    "\004\042\202\001\002\000\004\014\203\001\002\000\006" +
    "\012\204\013\205\001\002\000\004\052\213\001\002\000" +
    "\004\025\210\001\002\000\004\016\207\001\002\000\034" +
    "\006\uffec\010\uffec\011\uffec\017\uffec\020\uffec\021\uffec\023" +
    "\uffec\026\uffec\034\uffec\035\uffec\037\uffec\040\uffec\044\uffec" +
    "\001\002\000\022\006\027\010\024\011\026\026\uffcd\035" +
    "\032\037\031\040\033\044\036\001\002\000\004\026\212" +
    "\001\002\000\004\016\uffea\001\002\000\014\040\113\041" +
    "\110\045\100\046\115\047\101\001\002\000\004\053\216" +
    "\001\002\000\004\053\uffe9\001\002\000\004\025\217\001" +
    "\002\000\022\006\027\010\024\011\026\026\uffcd\035\032" +
    "\037\031\040\033\044\036\001\002\000\004\026\221\001" +
    "\002\000\006\012\204\013\205\001\002\000\004\016\uffeb" +
    "\001\002\000\016\017\uffd5\020\uffd5\021\uffd5\023\uffd5\026" +
    "\uffd5\034\uffd5\001\002\000\004\035\225\001\002\000\004" +
    "\040\226\001\002\000\004\027\227\001\002\000\010\040" +
    "\113\041\126\045\100\001\002\000\006\032\133\033\231" +
    "\001\002\000\004\040\232\001\002\000\004\032\233\001" +
    "\002\000\004\032\234\001\002\000\004\042\235\001\002" +
    "\000\004\014\236\001\002\000\022\006\027\010\024\011" +
    "\026\021\uffcd\035\032\037\031\040\033\044\036\001\002" +
    "\000\004\021\240\001\002\000\034\006\uffee\010\uffee\011" +
    "\uffee\017\uffee\020\uffee\021\uffee\023\uffee\026\uffee\034\uffee" +
    "\035\uffee\037\uffee\040\uffee\044\uffee\001\002\000\016\017" +
    "\uffd0\020\uffd0\021\uffd0\023\uffd0\026\uffd0\034\uffd0\001\002" +
    "\000\004\022\246\001\002\000\014\040\113\041\110\045" +
    "\100\046\115\047\101\001\002\000\004\024\245\001\002" +
    "\000\006\015\uffcc\022\uffcc\001\002\000\004\036\ufffe\001" +
    "\002\000\004\035\250\001\002\000\004\040\251\001\002" +
    "\000\006\033\ufffa\042\ufffc\001\002\000\022\006\027\010" +
    "\024\011\026\034\uffcd\035\032\037\031\040\033\044\036" +
    "\001\002\000\004\034\243\001\002\000\004\015\255\001" +
    "\002\000\004\002\ufff8\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\254\000\006\002\004\013\003\001\001\000\002\001" +
    "\001\000\004\003\006\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\020\014\021\013\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\004\024\005\034\006\037\010\036" +
    "\011\022\012\027\014\033\017\021\001\001\000\004\033" +
    "\241\001\001\000\022\004\024\005\034\006\037\010\036" +
    "\011\022\012\027\014\033\017\240\001\001\000\002\001" +
    "\001\000\022\004\024\005\034\006\037\010\036\011\022" +
    "\012\027\014\033\017\222\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\004\024\005\034\006\037\010\036" +
    "\011\022\012\027\014\033\017\166\001\001\000\002\001" +
    "\001\000\004\022\150\001\001\000\002\001\001\000\022" +
    "\004\024\005\034\006\037\010\036\011\022\012\027\014" +
    "\033\017\143\001\001\000\022\004\024\005\034\006\037" +
    "\010\036\011\022\012\027\014\033\017\142\001\001\000" +
    "\002\001\001\000\022\004\024\005\034\006\037\010\036" +
    "\011\022\012\027\014\033\017\074\001\001\000\024\004" +
    "\024\005\034\006\037\007\042\010\036\011\022\012\027" +
    "\014\033\017\040\001\001\000\002\001\001\000\002\001" +
    "\001\000\022\004\024\005\034\006\037\010\036\011\022" +
    "\012\027\014\033\017\043\001\001\000\002\001\001\000" +
    "\022\004\024\005\034\006\037\010\036\011\022\012\027" +
    "\014\033\017\072\001\001\000\002\001\001\000\012\016" +
    "\050\030\054\031\053\032\051\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\031\057\032\051\001\001\000\002\001\001\000\012\016" +
    "\061\030\054\031\053\032\051\001\001\000\002\001\001" +
    "\000\010\030\064\031\053\032\051\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\022\004\024" +
    "\005\034\006\037\010\036\011\022\012\027\014\033\017" +
    "\067\001\001\000\002\001\001\000\004\007\071\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\024\015\104\025\110\026\103\027\101" +
    "\034\076\035\113\036\111\037\106\043\102\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\020\015\120" +
    "\026\103\027\101\035\124\037\122\041\117\042\121\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\015\120\026\103\027" +
    "\101\037\122\041\117\001\001\000\002\001\001\000\010" +
    "\015\120\026\103\027\101\001\001\000\004\035\131\001" +
    "\001\000\002\001\001\000\006\037\122\041\117\001\001" +
    "\000\002\001\001\000\006\026\134\027\101\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\027\136\001\001" +
    "\000\002\001\001\000\004\037\141\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\022\015\104\026\103\027\101\034\076\035\113\036" +
    "\111\037\106\043\145\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\023\157\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\023\154\001\001" +
    "\000\002\001\001\000\022\015\104\026\103\027\101\034" +
    "\076\035\113\036\111\037\106\043\156\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\016\161\030\054\031" +
    "\053\032\051\001\001\000\002\001\001\000\002\001\001" +
    "\000\022\004\024\005\034\006\037\010\036\011\022\012" +
    "\027\014\033\017\164\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\016\170\030\054\031" +
    "\053\032\051\001\001\000\002\001\001\000\002\001\001" +
    "\000\022\004\024\005\034\006\037\010\036\011\022\012" +
    "\027\014\033\017\173\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\024\205" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\004\024\005\034\006\037" +
    "\010\036\011\022\012\027\014\033\017\210\001\001\000" +
    "\002\001\001\000\002\001\001\000\024\015\104\026\103" +
    "\027\101\034\076\035\113\036\111\037\106\040\213\043" +
    "\214\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\022\004\024\005\034\006\037\010\036\011" +
    "\022\012\027\014\033\017\217\001\001\000\002\001\001" +
    "\000\004\024\221\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\015\227\026\103\027\101\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\004\024\005" +
    "\034\006\037\010\036\011\022\012\027\014\033\017\236" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\015\104\026\103\027\101" +
    "\034\076\035\113\036\111\037\106\043\243\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\004" +
    "\024\005\034\006\037\010\036\011\022\012\027\014\033" +
    "\017\252\001\001\000\004\033\253\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public String error = "";
    public void syntax_error(Symbol s){
        error += "Error de sintaxis no se esperaba: "+ s.value +", en la linea: "+(s.left+1)+", columna: "+(s.right+1)+"\n";
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
        System.out.println("El programa contiene errores sintacticos no puede seguir");
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // VALORO ::= OPERACION 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALORO",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // VALORO ::= VALOR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALORO",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // VALOR ::= VALOR1 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // VALOR ::= ARREGLO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // VALOR ::= MATRIZ 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // VALOR1 ::= BOOL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR1",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // VALOR1 ::= CHAR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("VALOR1",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // MATRIZ1 ::= ARREGLO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATRIZ1",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // MATRIZ1 ::= MATRIZ1 COMA ARREGLO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATRIZ1",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // MATRIZ ::= ABREPAR MATRIZ1 CIERRAPAR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MATRIZ",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // ARREGLO1 ::= VALOR1 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ARREGLO1",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // ARREGLO1 ::= ARREGLO1 COMA VALOR1 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ARREGLO1",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // ARREGLO ::= ABREPAR ARREGLO1 CIERRAPAR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ARREGLO",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // RETORNO ::= RETURN VALORO FINLINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("RETORNO",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // CODE ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CODE",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // CODE ::= PRINTCOND CODE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CODE",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // CODE ::= OPTIONSCOND CODE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CODE",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // CODE ::= LOOPCOND CODE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CODE",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // CODE ::= FORCOND CODE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CODE",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // CODE ::= IFCOND ELSECOND CODE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CODE",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // CODE ::= IFCOND CODE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CODE",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // CODE ::= ASIGNACION CODE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CODE",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // CODE ::= DECLARACION CODE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CODE",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // COND3 ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COND3",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // COND3 ::= NOT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COND3",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // COND2 ::= ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COND2",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // COND2 ::= BOOL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COND2",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // COND2 ::= COND3 ABREPAR CONDICION CIERRAPAR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COND2",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // COND1 ::= COND2 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COND1",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // COND1 ::= COND1 ANDOR COND2 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("COND1",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // CONDICION ::= COND1 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CONDICION",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // CONDICION ::= CONDICION OPREL COND1 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("CONDICION",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // OP2 ::= ABREPAR OPERACION CIERRAPAR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OP2",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // OP2 ::= ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OP2",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // OP2 ::= INT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OP2",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // OP1 ::= OP2 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OP1",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // OP1 ::= OP1 OPMD OP2 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OP1",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // OPERACION ::= OP1 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPERACION",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // OPERACION ::= OPERACION OPSR OP1 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPERACION",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // PRINTER ::= STRING 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PRINTER",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // PRINTER ::= VALORO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PRINTER",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // PRINTCOND ::= PRINT ABREPAR PRINTER CIERRAPAR FINLINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PRINTCOND",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // OPTT2 ::= VALORO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPTT2",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // OPTT ::= DEFOPT ABRE CODE CIERRA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPTT",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // OPTT ::= OPT ABRECOR OPTT2 CIERRACOR ABRE CODE CIERRA OPTT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPTT",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // OPTIONSCOND ::= OPTIONS ABREPAR ID COMA TYPE CIERRAPAR BEGIN OPTT ENDO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("OPTIONSCOND",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // LOOPCOND ::= LOOP ABREPAR CONDICION CIERRAPAR BEGIN CODE ENDL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LOOPCOND",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // FORCOND ::= FOR ABREPAR TYPE ID HASTA OPERACION COMA ID OPSR OPSR CIERRAPAR BEGIN CODE ENDF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FORCOND",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-13)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // ELSECOND ::= ELSE BEGIN CODE ENDE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ELSECOND",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // ELSECOND ::= ELSE IF ABREPAR CONDICION CIERRAPAR BEGIN CODE ENDE ELSECOND 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ELSECOND",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // IFCOND ::= IF ABREPAR CONDICION CIERRAPAR BEGIN CODE ENDI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("IFCOND",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // ASIGNACION ::= ID ASIG VALORO FINLINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ASIGNACION",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // DECL2 ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECL2",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // DECL2 ::= ASIG VALORO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECL2",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // DECL ::= ID DECL2 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECL",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // DECL ::= DECL COMA ID DECL2 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECL",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // DECLARACION ::= TYPE DECL FINLINE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("DECLARACION",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // MAINCOND ::= FUNCION FUNC MAIN BEGIN CODE RETORNO ENDM 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("MAINCOND",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // LISTATYPES ::= TYPE ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTATYPES",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // LISTATYPES ::= LISTATYPES COMA TYPE ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTATYPES",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // LISTAPARAM ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTAPARAM",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // LISTAPARAM ::= LISTATYPES COMA TYPE ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTAPARAM",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // LISTAPARAM ::= TYPE ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("LISTAPARAM",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // FUNCION2 ::= FUNC TYPE ID ABREPAR LISTAPARAM CIERRAPAR BEGIN CODE RETORNO ENDFU 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUNCION2",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // FUNCION ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUNCION",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // FUNCION ::= FUNCION FUNCION2 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("FUNCION",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= MAINCOND EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

