
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 16 15:52:43 CST 2020
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FINLINE = 18;
  public static final int CHAR = 36;
  public static final int INT = 35;
  public static final int OPSR = 24;
  public static final int FOR = 6;
  public static final int ENDO = 12;
  public static final int HASTA = 21;
  public static final int ENDM = 11;
  public static final int NOT = 39;
  public static final int ENDL = 17;
  public static final int OPMD = 23;
  public static final int ENDI = 13;
  public static final int TYPE = 27;
  public static final int BOOL = 37;
  public static final int ENDF = 15;
  public static final int ENDE = 14;
  public static final int BEGIN = 10;
  public static final int OPREL = 3;
  public static final int LOOP = 4;
  public static final int MAIN = 5;
  public static final int IF = 29;
  public static final int ID = 30;
  public static final int EOF = 0;
  public static final int ASIG = 22;
  public static final int RETURN = 26;
  public static final int ENDFU = 16;
  public static final int error = 1;
  public static final int COMA = 25;
  public static final int ABRE = 19;
  public static final int CIERRACOR = 41;
  public static final int CIERRAPAR = 32;
  public static final int ABRECOR = 40;
  public static final int ANDOR = 2;
  public static final int ELSE = 33;
  public static final int FUNC = 28;
  public static final int ABREPAR = 31;
  public static final int DEFOPT = 9;
  public static final int STRING = 38;
  public static final int OPT = 8;
  public static final int CIERRA = 20;
  public static final int OPTIONS = 7;
  public static final int PRINT = 34;
}

