
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 20 21:36:40 CST 2020
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FINLINE = 19;
  public static final int CHAR = 37;
  public static final int INT = 36;
  public static final int OPSR = 25;
  public static final int FOR = 7;
  public static final int ENDO = 13;
  public static final int HASTA = 22;
  public static final int ENDM = 12;
  public static final int NOT = 40;
  public static final int ENDL = 18;
  public static final int AND = 2;
  public static final int OPMD = 24;
  public static final int ENDI = 14;
  public static final int TYPE = 28;
  public static final int OR = 3;
  public static final int BOOL = 38;
  public static final int ENDF = 16;
  public static final int ENDE = 15;
  public static final int BEGIN = 11;
  public static final int OPREL = 4;
  public static final int LOOP = 5;
  public static final int MAIN = 6;
  public static final int IF = 30;
  public static final int ID = 31;
  public static final int EOF = 0;
  public static final int ASIG = 23;
  public static final int RETURN = 27;
  public static final int ENDFU = 17;
  public static final int error = 1;
  public static final int COMA = 26;
  public static final int ABRE = 20;
  public static final int CIERRACOR = 42;
  public static final int CIERRAPAR = 33;
  public static final int ABRECOR = 41;
  public static final int ELSE = 34;
  public static final int FUNC = 29;
  public static final int READ = 43;
  public static final int ABREPAR = 32;
  public static final int DEFOPT = 10;
  public static final int STRING = 39;
  public static final int OPT = 9;
  public static final int CIERRA = 21;
  public static final int PRINT = 35;
  public static final int OPTIONS = 8;
}

