
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 15 11:11:58 CST 2020
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE = 27;
  public static final int OPT = 8;
  public static final int LOOP = 4;
  public static final int FINLINE = 12;
  public static final int ABREPAR = 25;
  public static final int HASTA = 15;
  public static final int NOT = 31;
  public static final int RETURN = 20;
  public static final int END = 11;
  public static final int IF = 23;
  public static final int ID = 24;
  public static final int BEGIN = 10;
  public static final int ANDOR = 2;
  public static final int STRING = 30;
  public static final int TYPE = 21;
  public static final int COMA = 19;
  public static final int OPSR = 18;
  public static final int CIERRAPAR = 26;
  public static final int FUNC = 22;
  public static final int EOF = 0;
  public static final int MAIN = 5;
  public static final int ABRE = 13;
  public static final int PRINT = 28;
  public static final int error = 1;
  public static final int CIERRA = 14;
  public static final int OPMD = 17;
  public static final int OPTIONS = 7;
  public static final int DEFOPT = 9;
  public static final int FOR = 6;
  public static final int OPREL = 3;
  public static final int VALOR = 29;
  public static final int ASIG = 16;
}

